version: '2.2'

services:

  kryptacmedb:
    image: mysql:5.6
    container_name: kryptacmedb.local
    environment:
      KRYPTACME_DATABASE_USER: root
      KRYPTACME_DATABASE_HOST: 127.0.0.1
      KRYPTACME_DATABASE_PORT: 3307
      KRYPTACME_DATABASE_PASSWORD: password
      SECRET_KEY_BASE: ac78b90016cdfd18801e08b146c2eb69d6bac46d44009259e9ccf9abe982f16fe8c745d8881538ca9dba2d5b0f9daf459db3c54d4a609b888b56703b3a81caeb
    networks:
      - mynetworks
    ports:
      - 3307:3306
    healthcheck:
      test: "(echo >/dev/tcp/localhost/3307)"

  kryptacme:
    image: tuxmonteiro/kryptacme
    container_name: kryptacme
    networks:
      - mynetworks
    ports:
      - 8081:8080
    depends_on:
      kryptacmedb:
        condition: service_healthy
      globodns:
        condition: service_started

  globodnsdb:
    image: mysql:5.6
    container_name: globodnsdb.local
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: globodns
    networks:
      - mynetworks
    ports:
      - 3306:3306
    healthcheck:
      test: "(echo >/dev/tcp/localhost/3306)"

  globodns:
    image: tuxmonteiro/globodns
    container_name: globodns
    networks:
      - mynetworks
    ports:
      - 8080:8080
      - 53:53/udp
    depends_on:
      globodnsdb:
        condition: service_healthy

networks:
  mynetworks:
