defaults: &defaults
  acme_endpoint: <%= ENV.fetch('ACME_ENDPOINT', 'https://127.0.0.1:14000/dir') %>
  gdns_endpoint: <%= ENV['GDNS_ENDPOINT'] %>
  gdns_token: <%= ENV['GDNS_TOKEN'] %>
  dest_crt: <%= ENV['DEST_CRT'] %>
  time_renewal: <%= ENV['TIME_RENEWAL'] %> #DAYS
  server_dns: <%= ENV['SERVER_DNS'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
