defaults: &defaults
  acme_endpoint: <%= ENV['ACME_ENDPOINT'] %>
  gdns_endpoint: <%= ENV['GDNS_ENDPOINT'] %>
  gdns_token: <%= ENV['GDNS_TOKEN'] %>
  dest_crt: <%= ENV['DEST_CRT'] %>
  time_renewal: <%= ENV['TIME_EXPIRATION'] %> #DAYS

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults