defaults: &defaults
  acme_endpoint: <%= ENV['ACME_ENDPOINT'] %>
  gdns_endpoint: <%= ENV['GDNS_ENDPOINT'] %>
  gdns_token: <%= ENV['GDNS_TOKEN'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults